# 异常处理与输入输出

## 异常

执行一下代码，显然地，数组越界，会出错误。

```java
package test;
public class Test {
	public static void main(String[] args) {
		int[] array = new int[10];
		array[10] = 10;//数组最大是 9 ，此处越界。
		System.out.println("ok");
	}
}
//可以看到运行后，控制栏出现异常: 
//Exception...java.lang.ArrayIndexOutOfBoundsException:...
```

当某行代码出现异常后，不会继续向下执行，而是出现异常。

使用 try{...}catch(...){...} 来捕捉异常。

```java
package test;
import java.util.Scanner;
public class Test {
	public static void main(String[] args) {
		int[] array = new int[10];
		Scanner in = new Scanner(System.in);
		int index = in.nextInt();
		try{
			array[index] = 10;
			System.out.println("ok");
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("catch exception");
		}
		System.out.println("outside");
		in.close();
	}
}
//当输入 9 时，输出结果为：
//ok
//outside
//当输入 10 时，输出结果为：
//catch exception
//outside
```

由测试结果可知，
当在 try{...} 中无异常时，执行 try{...} 中的代码后，不会执行 catch(...){...} 中的代码，而继续执行其后的代码。
当在 try{...} 中出现异常时，不会继续执行 try{...} 中异常位置后的代码，而是直接跳执行 catch(...){...} 中的代码，之后，继续执行后续代码。

### 捕捉异常机制

使用

```java
try{
	//可能产生异常的代码
}catch(type1 id1){
	//处理异常type1的代码
}catch(... ...){
	//处理异常...的代码
}catch(typen idn){
	//处理异常typen的代码
}
```

来捕捉异常。

当 try{...} 中出现异常时，则会寻找后面 catch(...) 中有无匹配的异常，如果有，则执行对应的 catch(...){...} 中的代码，而不会执行处理其他类型异常的 catch(...){...} 中的代码。
如果没有，控制栏就会报异常信息。

这里就不多举例了。

另外举例说明一下try{...} 中有调用函数，调用函数中出现异常的情况：

```java
package test;
public class Test {
	public static void func() {
		int[] array = new int[10];
		array[10] = 10;
		System.out.println("func");
	}
	public static void main(String[] args) {
		try{
			func();
			System.out.println("ok");
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("catch exception");
		}
		System.out.println("outside");
	}
}
//输出结果为：
//catch exception
//outside
```

这个例子说，在 try{...} 中调用函数，被调函数中出现了异常，同样的，不会执行被调函数出现异常处之后的代码，而是跳出被调函数，返回 try{...}，跳出 try{...}，进入对应的 catch(...){...} 中并执行代码。

至于被调函数又调用了其他函数，在其他函数中出现异常了，一层一层地退出来就好啦。

### 捕捉到异常后

除了在对应 catch(...){...} 执行一些代码，还可以查看该异常。

```java
package test;
public class Test {
	public static void g() {
		int[] array = new int[10];
		array[10] = 10;
		System.out.println("g");
	}
	public static void f() {
		g();
	}
	public static void main(String[] args) {
		try{
			f();
			System.out.println("ok");
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("catch exception");
			System.out.println(e.getMessage());
			System.out.println(e);
			e.printStackTrace();
		}
		System.out.println("outside");
	}
}
//输出结果为：
//catch exception
//下一行是 System.out.println(e.getMessage());
//Index 10 out of bounds for length 10
//下一行是 System.out.println(e);
//java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
//下四行是 e.printStackTrace();
//java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 10
//	  at exception.Exception.g(Exception.java:5)//显然5，9，13是各函数出现异常中断的位置
//	  at exception.Exception.f(Exception.java:9)
//	  at exception.Exception.main(Exception.java:13)
//outside
```

或者，在 catch(...){...}使用 throw ，再度抛出异常。

```java
package test;
public class Test {
	public static void f() {
		try{
			int[] array = new int[10];
			array[10] = 10;
			System.out.println("func");
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("catch exception in f()");
			throw e;//抛出异常
		}
	}
	public static void main(String[] args) {
		try{
			f();
			System.out.println("ok");
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("catch exception in main()");
		}
		System.out.println("outside");
	}
}
//抛出异常，输出结果为：
//catch exception in f()
//catch exception in main()
//outside
//如果注释掉，不抛出异常，输出结果为：
//catch exception in f()
//ok
//outside
```

可见，如果抛出异常，那么后续对应的 catch 仍然会检测到该异常；如果不抛出，就认为你已经在第一个对应的 catch 对这个异常进行处理了，后续的对应 catch 则不会再检测到该异常。

我顺带尝试了在抛出异常 throw e; 后面加代码，提示 unreachable code，会报错。

## 异常机制

### 异常声明

如果函数可能抛出异常，则必须在函数头部声明。

```java
package test;
class TooBig extends Throwable{...}
class TooSmall extends Throwable{...}
class DivZero extends Throwable{...}
public class Test {
	public static int test() {
		return -1;
	}
	static void func() throws TooBig,TooSmall,DivZero{
	//在函数头的声明中是 throws，要加第三人称单数
		if(test() == -1) throw new TooBig();
		else throw new TooSmall();
	}
	public static void main(String[] args){
		...
	}
}

```

因为 throw ...; 跟的必须是 Throwable 类或其子类，所以得自己定义继承类并继承自 Throwable。

注意，函数头的声明中是 throws，要加第三人称单数。因为是陈述句嘛。
代码使用 throw 就是祈使句嘛，所以不用加。

该例中，可以注意到，即便函数 func() 中根本就没有写抛出 throw new DivZero; 但在函数声明中，仍然可以写上 throws DivZero。

当一个函数有了抛出异常的声明，则调用该函数的地方需要使用 try...catch 语句捕获被调函数声明的异常，或者，在自己函数声明中，声明自己没有处理的异常。

```java
package test;
class TooBig extends Exception{}
class TooSmall extends Exception{}
class DivZero extends Exception{}
public class Test {
	public static int g() throws TooBig,TooSmall,DivZero {// g() 的声明有 3 个异常
		...
	}
	static void func() throws DivZero{// func() 的声明有 1 个未处理的异常
		try{
			g();// 调用了 g()，需要处理 g() 声明的异常
		}catch(TooBig e) {//处理了 g() 的 2 个异常
			...
		}catch(TooSmall e){
			...
		}
	}
	public static void main(String[] args){
		try{
			func();
           	//此处调用了 func()，需要处理 func() 声明的异常
		} catch (DivZero e) {// 处理 func() 声明的异常
			...
		}catch(ArrayIndexOutOfBoundsException e) {//顺手抓一个数组越界异常
            ...
		}
	}
}
```

已知能抛出的异常，类型必须是 Throwable 及其子类。

JAVA 中更常见使用的是 Exception 类，该类也继承自 Throwable。一般有两种写法。

```java
throw Exception();
throw Exception("help!");
```

### 子类异常的捕获

另外，catch 能够捕获异常的父类：

```java
package test;
class A extends Exception{}//A 继承至 Exception
class B extends A{}//B 继承至 A，是 A 的子类。
public class Test {
	public static int g() {
		return 2;
	}
	public static void func() throws A,B{
		if(g() == 1) throw new A();
		else if(g() == 2)throw new B();
	}
	public static void main(String[] args){
		try{
			func();
		} catch (A e) {//只捕获异常 A
			System.out.println("catch A");
		} 
	}
}
//输出结果为：
//catch B
```

说明，catch 捕获异常，可以捕获异常本身及其子类异常。
（我猜也许是因为向上造型是默认的，安全的）

如果将该例 catch 修改为：

```java
		} catch (B e) {//子类异常在前
			System.out.println("catch B");
		} catch (A e) {//父类异常在后
			System.out.println("catch A");
		}
//输出结果只有：
//catch B
```

如果将该例 catch 修改为：

```java
		} catch (A e) {//父类异常在前
			System.out.println("catch A");
		} catch (B e) {//子类异常在后//此处会提示 unreachable
			System.out.println("catch B");
		}
```

利用父类异常可以捕获自身及其子类异常，我们可以在 try...catch 语句最后使用：

```java
try{
	//可能产生异常的代码
}catch(type1 id1){
	//处理异常type1的代码
}catch(... ...){
	//处理异常...的代码
}catch(Exception e){//捕获前面没有考虑到的异常。
    //代码
}
```

这样就考虑周到了。

Exception 的子类中包括所有异常，包括一些系统运行时刻异常，而 ArrayIndexOutOfBoundsException 这类系统运行时刻异常是不需要声明的。
毕竟，因为这些运行时刻异常，太容易在代码各个地方出现。哪里都声明一次，就太繁琐，就默认了。
所以其实上面最后一个 catch 即便不用 Exception e，程序遇到异常也会在控制栏输出异常信息。就是因为这些运行时刻异常是不需要声明，自动考虑的。

### 异常声明遇到继承

当覆盖一个函数是，子类不能声明抛出比父类的版本更多的异常。
即，只能是父类版本声明的异常的类型及其子类。

```java
package test;
class A extends Exception{}//A 继承至 Exception
class B extends A{}//B 继承至 A，B 是 A 的子类。
class C extends Exception{}//C，继承至 Exception
public class Test {
	public static void f() throws A{
        ...
	}
	public static void main(String[] args){
		...
	}
}
class TestSon extends Test {
	public static void f() throws X{//此处的 X，写 (A),(B),(A,B) 都可以，但写 C 就不行。
        ...							//当然，也可以不抛出 throws
	}
}
```

因为如果子类的成员函数和父类的成员函数是覆盖关系，那么由于多态，我们是经常可能创建子类对象，向上造型赋给给父类指针的，例如在代码中：

```java
	Test t = new TestSon();
	t.f();
```

那么我们就只会处理在这里处理 t 的类型的函数 f() 声明的异常：

```java
	Test t = new TestSon();
	try{
		t.f();
	}catch(A e){
		....
	}
```

但实际运行时，调用的其实是子类的 f()，如果允许子类覆盖父类的 f() 拥有父类声明以外的异常（比如子类有异常 C），那么这里的 catch 就无法处理子类的新的异常了。所以子类覆盖父类的成员函数，不能拥有比父类成员函数更多的异常。

在子类的构造函数中，必须声明包含父类构造函数声明的全部异常，也可有超出父类构造函数的异常。

```java
package test;
class A extends Exception{}//A 继承至 Exception
class B extends A{}//B 继承至 A，是 A 的子类。
class C extends Exception{}//C，继承至 Exception
public class Test {
	public Test() throws A,B{//构造函数有抛出异常声明
        ...
	}
}
class TestSon extends Test {
	public TestSon() throws X{//此处 X 可为，(A),(A,B),(B,C),(A,B,C)
        ...					//不能不写，不能为 (B),(C),(B,C)
	}
	public static void f() throws A,B{
        ...
	}
}
```

子类的构造函数是会调用父类的构造函数，所以父类构造函数有的异常，子类构造函数必然有；子类构造函数有的异常，父类未必有。

## 流

### 流的基础类

InputStream，输入类

OutputStream，输出类

### 文件流

FileInputStream，文件输入类

FileOutputStream，文件输出类

```java
package test;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
public class Test {
	public static void main(String[] args){
		byte[] by = new byte[] {97,98,99,100,101,102,103,104,105,106,107};
		try {
			FileOutputStream out = new FileOutputStream("test.dat");
            //创建一个 FileOutputStream 对象，并在工作目录下，如无则创建 test.dat，如有则打开进行覆盖性写入。
			out.write(by);
			out.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
//结果，打开工作目录中的 test.dat，可以看到显示为 abcdefghij
```

不过现在一般咱不会用这，通常造轮子的人比较常用。

### 流过滤器

前面的文件流只能以字节来输出，通过流过滤器的方式，可以实现以其他类型输出，称为过滤流。

```java
package test;
import java.io.BufferedOutputStream;
import java.io.DataOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
public class Test {
	public static void main(String[] args){
		try {
			DataOutputStream out = new DataOutputStream (
					new BufferedOutputStream(
							new FileOutputStream("test.dat") ) );
            //new FileOutputStream("test.dat")，还是建立一个文件输出流。
            //new BufferedOutputStream(...)，给这个文件输出流创建缓冲区。
            //new DataOutputStream (...)，创建 DataOutputStream 对象
			int i = 97;
			out.writeInt(i);//把 i 以 int 类型输出
			out.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
//结果，打开工作目录中的 test.dat，可以看到显示为    a，a 前面是 3 个空格。
```

然后是输入的：

```java
package test;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
public class Test {
	public static void main(String[] args){
		try {
			DataOutputStream out = new DataOutputStream (
					new BufferedOutputStream(
							new FileOutputStream("test.dat") ) );
			int i = 97;
			int j = 98;
			out.writeInt(i);//把 i 以 int 类型输出
			out.writeInt(j);//把 i 以 int 类型输出
			out.close();
			DataInputStream in = new DataInputStream (
					new BufferedInputStream(
							new FileInputStream("test.dat") ) );
			//new FileInputStream("test.dat")，还是建立一个文件输入流。
            //new BufferedInputStream(...)，给这个文件输入流创建缓冲区。
            //new DataInputStream (...)，创建 DataInputStream 对象
            int k = 0;
			k = in.readInt();
			System.out.println("k = "+k);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
//结果为，打开工作目录中的 test.dat，可以看到显示为 ab
//控制栏显示 k = 97
```

其实从代码可以看出，还依靠字节流的实现。
（感觉上啊，我猜啊，就是对字节流进行了处理，按照我们效果要的类型的规则进行了处理。比如要 int 类型，那么就每 4 字节看作一个 int 。）

## 文本输入输出

前面已经可以处理字节流和 int 类型流了。

这里就是如何处理字符类型的流。

使用 ...Reader 和 ...Writer 来处理 Unicode 字符。
不过现在，文件不一定是 Unicode，也可能是其他，比如 Ascll 码、国标码；或者就算是 Unicode ，也可能是 UTF-8，而不是 UTF-16。

所以我们还是以字节流，然后流过滤器的方式来实现字符流。

```java
package test;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
public class Test {
	public static void main(String[] args){
		try {
			PrintWriter out = new PrintWriter (
					new BufferedWriter(
							new OutputStreamWriter(
									new FileOutputStream("test.txt") ) ) );
   			//new FileOutputStream("test.txt")，还是建立一个文件输出流。
			//new OutputStreamWriter(...)，看名字应该有 Writer 应该是将字节流变为字符流
            //new BufferedWriter(...)，给这个字符流创建缓冲区。
            //new PrintWriter(...)，创建 PrintWriter 对象
            //当没有指定的时候，输出的编码方式是操作系统默认的编码。
			int i = 123456;
			String s = "hello world";
			out.println(i);
			out.println(s);
			out.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
}
////结果为，打开工作目录中的 test.dat，可以看到显示为：
//hello world
//123456
//看这里，i 应该是自动转化为了字符输出，和 System.out.println(i) 也是输出显示字符而类似吧。
```

输入的：

```java
package test;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
public class Test {
	public static void main(String[] args){
		try {
			BufferedReader in = new BufferedReader(
					new InputStreamReader(
							new FileInputStream("src/test/Test.java")));
            //读入本文件
            //new FileInputStream(...);创建字节流
            //new InputStreamReader(...);字节流变为 Reader，以其指定编码方式来处理字节流，不给出则以默认方式。
			String line;
			while( (line = in.readLine()) != null) {
				System.out.println(line);
			}
            //每次读入一行，输出到控制栏。
			in.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
```

通常使用 BufferedReader 来读文件；
还可使用 LineNumberReader ，其允许读第几行，即可跳跃地读取文件。

FileReader 和 FileWriter 都是继承父类的方法。他们本身的类中没有重写父类的任何方法。实际上就是等价于他们的父类 outputStreamWriter，inputSteamReader
只是为了方便理解，一看就知道是用来写入字符文件的类。

#### 编码问题

对于文件，其编码方式可能并非与 InputStreamReader() 默认方式一致，所以通过指定 InputStreamReader() 的编码方式，来解决问题。

```java
package test;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
public class Test {
	public static void main(String[] args){
		try {
			BufferedReader in = new BufferedReader(
				new InputStreamReader(//指定InputStreamReader()以utf8的编码处理字节流
						new FileInputStream("test.txt"),"utf8"));
			String line;
			while( (line = in.readLine()) != null) {
				System.out.println(line);
			}
			in.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
//test.txt，内容为：善意谎言125，另存为 UTF-8 编码。
//如果不指定 InputStreamReader() 以 utf8 的编码处理字节流，读入，输出则是乱码：
//鍠勬剰璋庤█125
//指定为 utf8 后，读入，则正常输出：
//善意谎言125
```

### 格式化输入输出

PrintWriter 类，可用 print()，println()，以及printf("格式",...)，format("格式",...)。

Scanner 类，在 InputStream 或 Reader 上建立一个 Scanner 对象，可以从流中的文本解析出以文本表达的各种基本类型，next...()，比如 nextInt()。
就是文本里面是"数123"，通常我们希望 123 是作为 int 读入。而非字符或字符串存储。

选择输入用的类：
数据是二进制的（这里的二进制含义是指对你对数据流的操作以字节为单位）：用 ...InputStream；
数据是纯表示文本的（字符、字符串）：用 ...Reader；
数据不是纯表示文本的（比如上面举例的"数123"）：用 Scanner；

## 流的应用

### 计算机间发送/接收数据

向服务器发送流：

```java
package test;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
public class Test {
	public static void main(String[] args){
		try {
			Socket socket = new Socket(InetAddress.getByName("localhost"),12345);
            //localhost，本机；12345，端口号。
			PrintWriter out = new PrintWriter( 
					new BufferedWriter( 
							new OutputStreamWriter( 
									socket.getOutputStream())));
			out.println("hello");
			out.close();
			socket.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
//下载 netcat 软件。
//打开命令行 cmd，因为我是 windows，输入 nc -l -p 12345 使端口 12345 处于监听状态。
//允许这段代码，命令行中显示：
//hello
```

加上接收数据：

```java
package test;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
public class Test {
	public static void main(String[] args){
		try {
			Socket socket = new Socket(InetAddress.getByName("localhost"),12345);
			PrintWriter out = new PrintWriter( 
					new BufferedWriter( 
							new OutputStreamWriter( 
									socket.getOutputStream())));
			out.println("hello");
            //out.flush();//这里加上out.flush()，将 hello 冲出缓冲区使得先显示 hello
			BufferedReader in = new BufferedReader( 
					new InputStreamReader(
							socket.getInputStream()));
			String line;
			line = in.readLine();
			System.out.println(line);
			out.close();
			socket.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
	}
}
//还是 cmd 先允许 nc -l -p 12345，在运行这段代码
//结果是，先 cmd 没有输出东西，等 cmd 我输入了 nihao 回车后
//才显示
//C:\User\98099>nc -l -p 12345
//nihao
//hello
//然后在控制栏会显示出 nihao
```

这里 cmd 后显示 hello 是因为 hello在缓冲区中，最后关闭 out.close() 时才冲出缓冲区，显示。

所以加上一句 out.flush()，冲出缓冲区就行了。

显然可以注意到，当在 cmd 输入的时间段，整个程序是阻塞的，知道等待输入结束才唤醒。
所以如果希望程序不因等待输入而阻塞，那么就多线程，开一个线程去等待输入，其他线程可以继续与该输入无需求关系的指令。
或者用 nio 的 channel 选择机制。

### 对象串行化

上面讲的都是读写数据，那么如果需要的读写的是 JAVA 中的对象呢，能写出吗，能重新读入吗。

```java
package test;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
class Student implements Serializable{
	private String name;
	private int age;
	private int grade;
	public Student(String name, int age, int grade) {
		this.name = name;
		this.age = age;
		this.grade = grade;
	}
	public String toString() {
		return name+" "+age+" "+grade;
	}
	
}
public class Test {
	public static void main(String[] args){
		try {
			Student s1 = new Student("Lin",12,3);
			ObjectOutputStream out = new ObjectOutputStream(
					new FileOutputStream("obj.dat"));
			out.writeObject(s1);
			out.close();
			ObjectInputStream in = new ObjectInputStream(
					new FileInputStream("obj.dat"));
			Student s2 = (Student)in.readObject();
			System.out.println(s2);
			in.close();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
				e.printStackTrace();
		}
	}
}
//工作目录下的 obj.dat，打开，内容为：
// sr test.Studentu2?甴 I ageI gradeL namet Ljava/lang/String;xp      t Lin
//控制栏显示为：
//Lin 12 3
```

还是能看出，确实存储了 s1 的信息，除了 name、age、grade 外，还有一些其他信息，是用来标示的，用于读入时知道这个信息是是什么样子的对象。

2021.01.16